-- Migration 011 — Reminder phrasing (ADR-0021)
--
-- Adds `reminder_phrase`: a natural, specific-recall check-in line generated
-- by the commitment parser alongside `text`/`due_at` (e.g. "You said you'd
-- start interview prep at 2:30 — starting?"), used at reminder delivery time
-- instead of a raw templated echo of `text`.
--
-- Nullable with NO default (unlike group_name's DEFAULT ''): NULL here
-- specifically means "not yet generated by this feature" (e.g. commitments
-- created before this migration), which callers must distinguish from an
-- empty string so they know to fall back to the old templated string. A
-- one-time backfill script (backend/scripts/backfill_reminder_phrases.py)
-- populates this for existing open commitments.

ALTER TABLE commitments ADD COLUMN reminder_phrase TEXT;
